name: Build

on: [push, pull_request]

jobs:

  build_sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.platform_id }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            platform_id: win_amd64
            cairo_plat: x64
          - os: windows-2019
            platform_id: win32
            cairo_plat: x86
          - os: windows-2019
            platform_id: win_arm64
            cairo_plat: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_ARCHS_WINDOWS: "x86 ARM64 AMD64"
          CIBW_BEFORE_BUILD: "python {package}/.ci/download-cairo-win32.py ${{ matrix.cairo_plat }}"
          CIBW_BUILD: cp38-${{ matrix.platform_id }} cp39-${{ matrix.platform_id }} cp310-${{ matrix.platform_id }} cp311-${{ matrix.platform_id }} cp312-${{ matrix.platform_id }}
          CIBW_TEST_REQUIRES: pytest==7.4.4 hypothesis==6.98.3 attrs==23.2.0
          CIBW_TEST_COMMAND: bash {package}/.ci/test-wheels.sh {package}
          CIBW_TEST_SKIP: "*-win_arm64"
          CIBW_ENVIRONMENT_WINDOWS: PKG_CONFIG_PATH='${{ github.workspace }}/cairo-prebuild/lib/pkgconfig' PKG_CONFIG='${{ github.workspace }}/cairo-prebuild/bin/pkgconf.exe'

      - uses: actions/upload-artifact@v4
        with:
          name: "wheel-${{ matrix.cairo_plat }}"
          path: ./wheelhouse/*.whl
